// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddMastoWordController from "./add_masto_word_controller.js"
application.register("add-masto-word", AddMastoWordController)

import AddTwitterWordController from "./add_twitter_word_controller.js"
application.register("add-twitter-word", AddTwitterWordController)
